#----all functions!-----
functions:
  user:
    handler: functions/handler.user
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "cognito-idp:Admin*"
          - "cognito-idp:*User"
          - "cognito-idp:*Group"
        Resource: !GetAtt CognitoUserPool.Arn
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:DeleteItem"
          - "dynamodb:Query"
          - "dynamodb:Scan"
        Resource:
          - !GetAtt ItemsTable.Arn
          - !GetAtt WarehousesTable.Arn
          - !GetAtt TransactionsTable.Arn
          - !GetAtt InventoryTable.Arn
    events:
      - http:
          path: user
          method: post